import Head from 'next/head'
import * as Svg from '../src/SvgComponents'

export default function Home() {
  return (
    <>

      <Head>
        <title>Next Starter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* TODO: Navbar */}

      <Section>
      
        <div className='w-full border border-hanPurple'>
          <h1 className='text-7xl text-eerieBlack font-roboto font-bold'>Great feedback<br/>towards more clarity</h1>
        </div>

        <div className='w-full border border-hanPurple flex flex-row items-center justify-evenly border'>

          <div className='w-full flex flex-col border border-frenchSkyBlue'>

            <div className='w-full my-5 border border-darkElectricBlue'>
              <p className='text-eerieBlack'>We are here to help companies to evaluate their performance by combining goal tracking with peer feedback, 1-on-1 coaching, recognition and modern performance reviews.</p>
            </div>

            <button 
              className='w-full my-5 flex justify-center border border-hanPurple bg-hanPurple py-2 text-white hover:bg-white hover:text-hanPurple transition-all duration-200'
            >Get free demo</button>

          </div>

          <div className='basis-2/3 w-full'>
            <Svg.WorkTimeGraphic />
          </div>
        </div>

      </Section>

      <Section>
        <div className='w-full border border-hanPurple flex justify-center'>
          <h2 className='text-4xl text-eerieBlack font-roboto font-bold'>Scale-up with ease</h2>
        </div>

        <div className='w-full border border-hanPurple flex flex-row justify-evenly'>

          <div className='flex-1 flex-col justify-evenly p-2'>
            <div className='w-1/2'>
              <Svg.MessageIcon />
            </div>
            <h3 className='text-xl text-eerieBlack font-roboto font-bold'>Create</h3>
            <p className='text-eerieBlack'>Create feedback for the specified quarters by tagging and classification within the peers.</p>
          </div>

          <div className='flex-1 flex-col justify-evenly p-2'>
            <div className='w-1/2'>
              <Svg.GroupsIcon />
            </div>
            <h3 className='text-xl text-eerieBlack font-roboto font-bold'>Prioritize</h3>
            <p className='text-eerieBlack'>Prioritize & communicate effectively with every employee for the desired goals.</p>
          </div>

          <div className='flex-1 flex-col justify-evenly p-2'>
            <div className='w-1/2'>
              <Svg.DescriptionIcon />
            </div>
            <h3 className='text-xl text-eerieBlack font-roboto font-bold'>Post</h3>
            <p className='text-eerieBlack'>Post the desired feedback for the team and keep goal tracking accordingly.</p>
          </div>

        </div>
      </Section>

      <SectionWithBg bgColor="cornsilk">
        <div className='w-full border border-hanPurple'>
          <h1 className='text-7xl text-eerieBlack font-roboto font-bold'>
            How feedify stands out <span className='text-hanPurple'>different</span>
          </h1>
        </div>

        <div className='w-full border border-hanPurple'>
          <p className='text-eerieBlack'>A great review helps your employees identify growth opportunities and potential areas of improvement without damaging employee-manager relations, but writing a stron review isn't easy. feedify helps to improve the process of leadership skills and the ability to manage others to drive emplyee success.</p>
        </div>

      </SectionWithBg>


      <img className='w-full' src='video-placeholder.png'/>


      <SectionWithBg bgColor="hanPurple">

      <div className='w-full border border-hanPurple flex flex-row justify-evenly'>

          <div className='flex-1 flex-col justify-evenly p-2'>
            <h3 className='text-5xl text-white font-roboto font-bold'>10+</h3>
            <p className='text-white'>Years in business</p>
          </div>

          <div className='flex-1 flex-col justify-evenly p-2'>
            <h3 className='text-5xl text-white font-roboto font-bold'>500+</h3>
            <p className='text-white'>Happy customers</p>
          </div>

          <div className='flex-1 flex-col justify-evenly p-2'>
            <h3 className='text-5xl text-white font-roboto font-bold'>2500+</h3>
            <p className='text-white'>Successful deployments</p>
          </div>

        </div>

      </SectionWithBg>

      <Section>
        <div className='w-full border border-hanPurple'>
          <h1 className='text-6xl font-roboto font-bold'>Empower your whole team with user insights</h1>
        </div>

        <div className='w-full border border-hanPurple flex flex-row items-center justify-evenly border'>

          <div className='w-full flex flex-col border border-frenchSkyBlue'>

            <div className='w-full my-5 border border-darkElectricBlue'>
              <p>Keep your team in the loop. Collaborate with stakeholders in feedify and watch meaningful insights fuel business growth and team outcomes.</p>
            </div>

            <button 
              className='w-full my-5 flex justify-center border border-hanPurple bg-hanPurple py-2 text-white hover:bg-white hover:text-hanPurple transition-all duration-200'
            >Learn More</button>

          </div>

          <div className='basis-2/3 w-full'>
            <Svg.AnalyticsGraphic />
          </div>
        </div>

      </Section>

      <SectionWithBg bgColor="cornsilk">
        <div className='w-full border border-hanPurple flex justify-center'>
          <h2 className='text-4xl font-roboto font-bold'>Client testimonials</h2>
        </div>
      </SectionWithBg>

      <Section>
        <div className='w-full border border-hanPurple'>
          <h1 className='text-6xl font-roboto font-bold'>Want to know more? Let's talk</h1>
        </div>

        <div className='w-full border border-hanPurple flex flex-row items-center justify-evenly border'>

          <div className='basis-1/2 w-full'>
            <Svg.HighFiveGraphic />
          </div>


        </div>

      </Section>

      {/* TODO: Footer */}

    </>
  )
}

function Section({children}) { 
  return (
    <div className='w-full mx-0 my-12 px-24 items-center flex flex-col'>
      {children}
    </div>
  )
}

function SectionWithBg({children, bgColor}) {
  let className = `bg-${bgColor} w-full m-0 py-12 px-24 items-center flex flex-col`
  return (
    <div className={className}>
      {children}
    </div>
  )
}