import Head from 'next/head'
import HighFiveSvg from '../src/svgs/HighFiveSvg'
import WorkTimeSvg from '../src/svgs/WorkTimeSvg'
import AnalyticsSvg from '../src/svgs/AnalyticsSvg'

export default function Home() {
  return (
    <>

      <Head>
        <title>Next Starter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Section>
        <div className='w-full border border-hanPurple'>
          <h1 className='text-6xl font-roboto mb-5 font-bold'>Great feedback towards more clarity</h1>
        </div>
        <div className='w-full border border-hanPurple flex flex-row items-center'>

          <div className='basis-1/3 flex flex-col '>

            <div className='w-full my-5'>
              <p>We are here to help companies to evaluate their performance by combining goal tracking with peer feedback, 1-on-1 coaching, recognition and modern performance reviews.</p>
            </div>

            <div className='w-full my-5 flex justify-center'>
              <p>Get free demo</p>
            </div>

          </div>

          <div className='flex w-full'>
            <WorkTimeSvg />
          </div>
        </div>
      </Section>

    </>
  )
}


function Section({children}) {
  return (
    <div className='w-full mx-0 px-24 items-center flex flex-col'>
      {children}
    </div>
  )
}